

<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>qmt.geometry.freecad.fileIO &mdash; QMT 1.0 documentation</title>
  

  
  
    <link rel="shortcut icon" href="../../../../_static/favicon.ico"/>
  
  
  

  

  
  
    

  

  <link rel="stylesheet" href="../../../../_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="../../../../_static/pygments.css" type="text/css" />
    <link rel="index" title="Index" href="../../../../genindex.html" />
    <link rel="search" title="Search" href="../../../../search.html" /> 

  
  <script src="../../../../_static/js/modernizr.min.js"></script>

</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">

    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search">
          

          
            <a href="../../../../index.html" class="icon icon-home"> QMT
          

          
            
            <img src="../../../../_static/logo.png" class="logo" alt="Logo"/>
          
          </a>

          
            
            
              <div class="version">
                1.0
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../../../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <p class="caption"><span class="caption-text">Contents:</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../../../rst/tutorial.html">Tutorial</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../../rst/dev_overview.html">Structure of QMT</a></li>
</ul>

            
          
        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../../../index.html">QMT</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="../../../../index.html">Docs</a> &raquo;</li>
        
          <li><a href="../../../index.html">Module code</a> &raquo;</li>
        
      <li>qmt.geometry.freecad.fileIO</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
      </li>
    
  </ul>

  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <h1>Source code for qmt.geometry.freecad.fileIO</h1><div class="highlight"><pre>
<span></span><span class="c1"># Copyright (c) Microsoft Corporation. All rights reserved.</span>
<span class="c1"># Licensed under the MIT License.</span>

<span class="sd">&quot;&quot;&quot;Functions that deal with file i/o.&quot;&quot;&quot;</span>


<span class="kn">import</span> <span class="nn">FreeCAD</span>
<span class="kn">import</span> <span class="nn">Part</span>
<span class="kn">import</span> <span class="nn">Mesh</span>
<span class="kn">import</span> <span class="nn">qmt</span> <span class="k">as</span> <span class="nn">QMT</span>


<span class="c1"># ~ def setupModelFile(fileName):</span>
    <span class="c1"># ~ &#39;&#39;&#39; Makes an empty json model file and sets up a spreadsheet to sync with it.</span>
    <span class="c1"># ~ &#39;&#39;&#39;</span>
    <span class="c1"># ~ doc = FreeCAD.ActiveDocument</span>
    <span class="c1"># ~ objList = doc.Objects</span>
    <span class="c1"># ~ objNames = [x.Name for x in objList]</span>
    <span class="c1"># ~ if &#39;modelFilePath&#39; in objNames:</span>
        <span class="c1"># ~ doc.removeObject(&#39;modelFilePath&#39;)</span>
    <span class="c1"># ~ doc.recompute()</span>
    <span class="c1"># ~ spreadSheet = doc.addObject(&#39;Spreadsheet::Sheet&#39;, &#39;modelFilePath&#39;)</span>
    <span class="c1"># ~ spreadSheet.set(&#39;A1&#39;, &#39;Path to model file:&#39;)</span>
    <span class="c1"># ~ spreadSheet.set(&#39;B1&#39;, fileName)</span>
    <span class="c1"># ~ spreadSheet.setAlias(&#39;B1&#39;, &#39;modelFilePath&#39;)</span>
    <span class="c1"># ~ spreadSheet.setColumnWidth(&#39;A&#39;, 200)</span>
    <span class="c1"># ~ myModelFile = QMT.Model(modelPath=fileName)</span>
    <span class="c1"># ~ myModelFile.loadModel()</span>
    <span class="c1"># ~ myModelFile.saveModel()</span>
    <span class="c1"># ~ doc.recompute()</span>


<span class="c1"># ~ def getModel():</span>
    <span class="c1"># ~ &#39;&#39;&#39; return the model file associated with the current FreeCAD document.</span>
    <span class="c1"># ~ &#39;&#39;&#39;</span>
    <span class="c1"># ~ modelPath = FreeCAD.ActiveDocument.modelFilePath.modelFilePath</span>
    <span class="c1"># ~ myModel = QMT.Model(modelPath=modelPath)</span>
    <span class="c1"># ~ myModel.loadModel()</span>
    <span class="c1"># ~ return myModel</span>


<div class="viewcode-block" id="exportMeshed"><a class="viewcode-back" href="../../../../source/qmt.geometry.freecad.html#qmt.geometry.freecad.fileIO.exportMeshed">[docs]</a><span class="k">def</span> <span class="nf">exportMeshed</span><span class="p">(</span><span class="n">obj</span><span class="p">,</span> <span class="n">fileName</span><span class="p">):</span>
    <span class="sd">&#39;&#39;&#39; Export a mesh of an object to the given file name.</span>
<span class="sd">    &#39;&#39;&#39;</span>
    <span class="c1"># These previous methods use more complicated routines (netgen or mefisto)</span>
    <span class="c1"># that produce more controllable meshes but sometimes fail.</span>
    <span class="c1"># meshedObj = FreeCAD.ActiveDocument.addObject(&quot;Mesh::Feature&quot;,obj.Name+&quot;_mesh&quot;)</span>
    <span class="c1"># meshedObj.Mesh=MeshPart.meshFromShape(Shape=obj.Shape,Fineness=0,SecondOrder=0,Optimize=0,AllowQuad=0)</span>
    <span class="c1"># meshedObj.Mesh=Mesh.Mesh(obj.Shape.tessellate(0.01))</span>
    <span class="c1"># meshedObj.Mesh.write(fileName,&quot;STL&quot;,meshedObj.Name)</span>
    <span class="n">meshedObj</span> <span class="o">=</span> <span class="n">Mesh</span><span class="o">.</span><span class="n">export</span><span class="p">([</span><span class="n">obj</span><span class="p">],</span> <span class="n">fileName</span><span class="p">)</span>
    <span class="k">return</span> <span class="n">meshedObj</span></div>


<div class="viewcode-block" id="exportCAD"><a class="viewcode-back" href="../../../../source/qmt.geometry.freecad.html#qmt.geometry.freecad.fileIO.exportCAD">[docs]</a><span class="k">def</span> <span class="nf">exportCAD</span><span class="p">(</span><span class="n">obj</span><span class="p">,</span> <span class="n">fileName</span><span class="p">):</span>
    <span class="sd">&#39;&#39;&#39; Export a STEP (Standard for the Exchange of Product Data) 3D CAD file</span>
<span class="sd">    for the object.</span>
<span class="sd">    &#39;&#39;&#39;</span>
    <span class="c1"># The export format is determined by the extension, so we should check it:</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">fileName</span><span class="p">[</span><span class="o">-</span><span class="mi">5</span><span class="p">:]</span> <span class="o">==</span> <span class="s1">&#39;.step&#39;</span><span class="p">)</span> <span class="ow">or</span> <span class="p">(</span><span class="n">fileName</span><span class="p">[</span><span class="o">-</span><span class="mi">4</span><span class="p">:]</span> <span class="o">==</span> <span class="s1">&#39;.stp&#39;</span><span class="p">):</span>
        <span class="n">Part</span><span class="o">.</span><span class="n">export</span><span class="p">([</span><span class="n">obj</span><span class="p">],</span> <span class="n">fileName</span><span class="p">)</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span>
            <span class="s1">&#39;The file path&#39;</span> <span class="o">+</span> <span class="n">fileName</span> <span class="o">+</span>
            <span class="s1">&#39; does not end in .step or .stp. </span><span class="se">\</span>
<span class="s1">                          Please fix this and try your export again.&#39;</span><span class="p">)</span></div>


<span class="c1"># TODO: this is general, not fileIO</span>
<div class="viewcode-block" id="updateParams"><a class="viewcode-back" href="../../../../source/qmt.geometry.freecad.html#qmt.geometry.freecad.fileIO.updateParams">[docs]</a><span class="k">def</span> <span class="nf">updateParams</span><span class="p">(</span><span class="n">doc</span><span class="p">,</span> <span class="n">paramDict</span><span class="p">):</span>
    <span class="sd">&#39;&#39;&#39; Update the parameters in the modelParams spreadsheet to reflect the</span>
<span class="sd">        current value in the dict.</span>
<span class="sd">    &#39;&#39;&#39;</span>
    <span class="c1"># ~ doc = FreeCAD.ActiveDocument</span>

    <span class="c1"># ~ if passModel is None:</span>
        <span class="c1"># ~ myModel = getModel()</span>
    <span class="c1"># ~ else:</span>
        <span class="c1"># ~ myModel = passModel</span>
    <span class="c1"># ~ paramDict = myModel.modelDict[&#39;geometricParams&#39;]</span>
    
    <span class="c1"># We only want to do something if geometric parameters are defined</span>
    <span class="c1"># in the model. This means that if we have old parameters sitting</span>
    <span class="c1"># in the FreeCAD file, they won&#39;t get wiped out if we comment out</span>
    <span class="c1"># a geometry sweep in the model script.</span>
    <span class="k">if</span> <span class="n">paramDict</span><span class="p">:</span>
        <span class="c1"># Internal: unconditional removeObject on spreadSheet breaks param dependencies.</span>
        <span class="c1"># ~ spreadSheet = doc.addObject(&#39;Spreadsheet::Sheet&#39;, &#39;modelParams&#39;)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="n">spreadSheet</span> <span class="o">=</span> <span class="n">doc</span><span class="o">.</span><span class="n">modelParams</span>
            <span class="n">spreadSheet</span><span class="o">.</span><span class="n">clearAll</span><span class="p">()</span>  <span class="c1"># clear existing spreadsheet</span>
        <span class="k">except</span><span class="p">:</span>
            <span class="n">doc</span><span class="o">.</span><span class="n">removeObject</span><span class="p">(</span><span class="s1">&#39;modelParams&#39;</span><span class="p">)</span>  <span class="c1"># otherwise it was not a good spreadsheet</span>
            <span class="n">spreadSheet</span> <span class="o">=</span> <span class="n">doc</span><span class="o">.</span><span class="n">addObject</span><span class="p">(</span><span class="s1">&#39;Spreadsheet::Sheet&#39;</span><span class="p">,</span> <span class="s1">&#39;modelParams&#39;</span><span class="p">)</span>
        <span class="n">spreadSheet</span><span class="o">.</span><span class="n">set</span><span class="p">(</span><span class="s1">&#39;A1&#39;</span><span class="p">,</span> <span class="s1">&#39;paramName&#39;</span><span class="p">)</span>
        <span class="n">spreadSheet</span><span class="o">.</span><span class="n">set</span><span class="p">(</span><span class="s1">&#39;B1&#39;</span><span class="p">,</span> <span class="s1">&#39;paramValue&#39;</span><span class="p">)</span>
        <span class="n">spreadSheet</span><span class="o">.</span><span class="n">setColumnWidth</span><span class="p">(</span><span class="s1">&#39;A&#39;</span><span class="p">,</span> <span class="mi">200</span><span class="p">)</span>
        <span class="n">spreadSheet</span><span class="o">.</span><span class="n">setStyle</span><span class="p">(</span><span class="s1">&#39;A1:B1&#39;</span><span class="p">,</span> <span class="s1">&#39;bold&#39;</span><span class="p">,</span> <span class="s1">&#39;add&#39;</span><span class="p">)</span>
        <span class="k">for</span> <span class="n">i</span><span class="p">,</span> <span class="n">key</span> <span class="ow">in</span> <span class="nb">enumerate</span><span class="p">(</span><span class="n">paramDict</span><span class="p">):</span>
            <span class="n">paramType</span> <span class="o">=</span> <span class="n">paramDict</span><span class="p">[</span><span class="n">key</span><span class="p">][</span><span class="mi">1</span><span class="p">]</span>
            <span class="k">if</span> <span class="n">paramType</span> <span class="o">==</span> <span class="s1">&#39;freeCAD&#39;</span><span class="p">:</span>
                <span class="n">idx</span> <span class="o">=</span> <span class="nb">str</span><span class="p">(</span><span class="n">i</span> <span class="o">+</span> <span class="mi">2</span><span class="p">)</span>
                <span class="n">spreadSheet</span><span class="o">.</span><span class="n">set</span><span class="p">(</span><span class="s1">&#39;A&#39;</span> <span class="o">+</span> <span class="n">idx</span><span class="p">,</span> <span class="n">key</span><span class="p">)</span>
                <span class="n">spreadSheet</span><span class="o">.</span><span class="n">set</span><span class="p">(</span><span class="s1">&#39;B&#39;</span> <span class="o">+</span> <span class="n">idx</span><span class="p">,</span> <span class="nb">str</span><span class="p">(</span><span class="n">paramDict</span><span class="p">[</span><span class="n">key</span><span class="p">][</span><span class="mi">0</span><span class="p">]))</span>
                <span class="n">spreadSheet</span><span class="o">.</span><span class="n">setAlias</span><span class="p">(</span><span class="s1">&#39;B&#39;</span> <span class="o">+</span> <span class="n">idx</span><span class="p">,</span> <span class="nb">str</span><span class="p">(</span><span class="n">key</span><span class="p">))</span>
            <span class="k">elif</span> <span class="n">paramType</span> <span class="o">==</span> <span class="s1">&#39;python&#39;</span><span class="p">:</span>
                <span class="k">pass</span>
            <span class="k">else</span><span class="p">:</span>
                <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;Unknown geometric parameter type.&#39;</span><span class="p">)</span>
        
        <span class="n">doc</span><span class="o">.</span><span class="n">recompute</span><span class="p">()</span></div>


<span class="c1"># ~ def updateParams(passModel=None):</span>
    <span class="c1"># ~ &#39;&#39;&#39; Update the parameters in the modelParams spreadsheet to reflect the</span>
        <span class="c1"># ~ current value in the model file.</span>
    <span class="c1"># ~ &#39;&#39;&#39;</span>
    <span class="c1"># ~ doc = FreeCAD.ActiveDocument</span>
    <span class="c1"># ~ if passModel is None:</span>
        <span class="c1"># ~ myModel = getModel()</span>
    <span class="c1"># ~ else:</span>
        <span class="c1"># ~ myModel = passModel</span>
    <span class="c1"># ~ paramDict = myModel.modelDict[&#39;geometricParams&#39;]</span>
    <span class="c1"># ~ # We only want to do something if geometric parameters are defined</span>
    <span class="c1"># ~ # in the model. This means that if we have old parameters sitting</span>
    <span class="c1"># ~ # in the FreeCAD file, they won&#39;t get wiped out if we comment out</span>
    <span class="c1"># ~ # a geometry sweep in the model script.</span>
    <span class="c1"># ~ if paramDict:</span>
        <span class="c1"># ~ # Internal: unconditional removeObject on spreadSheet breaks param dependencies.</span>
        <span class="c1"># ~ try:</span>
            <span class="c1"># ~ spreadSheet = doc.modelParams</span>
            <span class="c1"># ~ spreadSheet.clearAll()  # clear existing spreadsheet</span>
        <span class="c1"># ~ except:</span>
            <span class="c1"># ~ doc.removeObject(&#39;modelParams&#39;)  # otherwise it was not a good spreadsheet</span>
            <span class="c1"># ~ spreadSheet = doc.addObject(&#39;Spreadsheet::Sheet&#39;, &#39;modelParams&#39;)</span>
        <span class="c1"># ~ spreadSheet.set(&#39;A1&#39;, &#39;paramName&#39;)</span>
        <span class="c1"># ~ spreadSheet.set(&#39;B1&#39;, &#39;paramValue&#39;)</span>
        <span class="c1"># ~ spreadSheet.setColumnWidth(&#39;A&#39;, 200)</span>
        <span class="c1"># ~ spreadSheet.setStyle(&#39;A1:B1&#39;, &#39;bold&#39;, &#39;add&#39;)</span>
        <span class="c1"># ~ for i, key in enumerate(paramDict):</span>
            <span class="c1"># ~ paramType = paramDict[key][1]</span>
            <span class="c1"># ~ if paramType == &#39;freeCAD&#39;:</span>
                <span class="c1"># ~ idx = str(i + 2)</span>
                <span class="c1"># ~ spreadSheet.set(&#39;A&#39; + idx, key)</span>
                <span class="c1"># ~ spreadSheet.set(&#39;B&#39; + idx, str(paramDict[key][0]))</span>
                <span class="c1"># ~ spreadSheet.setAlias(&#39;B&#39; + idx, str(key))</span>
            <span class="c1"># ~ elif paramType == &#39;python&#39;:</span>
                <span class="c1"># ~ pass</span>
            <span class="c1"># ~ else:</span>
                <span class="c1"># ~ raise ValueError(&#39;Unknown geometric parameter type.&#39;)</span>
        <span class="c1"># ~ doc.recompute()</span>
</pre></div>

           </div>
           
          </div>
          <footer>
  

  <hr/>

  <div role="contentinfo">
    <p>
        &copy; Copyright 2018, Microsoft Corporation.

    </p>
  </div>
  Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  


  

    <script type="text/javascript">
        var DOCUMENTATION_OPTIONS = {
            URL_ROOT:'../../../../',
            VERSION:'1.0',
            LANGUAGE:'None',
            COLLAPSE_INDEX:false,
            FILE_SUFFIX:'.html',
            HAS_SOURCE:  true,
            SOURCELINK_SUFFIX: '.txt'
        };
    </script>
      <script type="text/javascript" src="../../../../_static/jquery.js"></script>
      <script type="text/javascript" src="../../../../_static/underscore.js"></script>
      <script type="text/javascript" src="../../../../_static/doctools.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

  

  <script type="text/javascript" src="../../../../_static/js/theme.js"></script>

  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>